spring:
  application:
    name: config
  #git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yugenhai108/spring-cloud.git
          #对应git 分支名称
          default-label: master
          password: enen
          username: yugenhai108
          #对应搜索的文件夹路径
          searchPaths: config

#eureka-gateway-monitor-config 每个端口+1
server:
  port: 8701

#eureka注册配置
eureka:
  instance:
    #使用IP注册
    prefer-ip-address: true
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8700/eureka/
