language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11


install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2/