spring:
  profiles:
    active: dev

  # As Spring Cloud Ribbon is in maintenance mode
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

# Jetty / Reactive
coral:
  jetty:
    config:
      enabled: true
    initial-value:
      max-thread: 500
      min-thread: 20
  reactive:
    request:
      enabled: true