spring:
  application:
    name: gateway

#eureka-gateway-monitor-config 每个端口+1
server:
  port: 8702

#eureka注册配置
eureka:
  instance:
    #使用IP注册
    prefer-ip-address: true
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 30
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8700/eureka/

#route connection
zuul:
  host:
    max-per-route-connections: 20
    max-total-connections: 200
  #path
  routes:
    api-product.path: /pro/**
    api-product.serviceId: product
    api-customer.path: /cust/**
    api-customer.serviceId: customer


#断路时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000

#负载时间
ribbon:
  ReadTimeout: 60000
  SocketTimeout: 60000
