#port
server:
  port: 8707
#setting
spring:
  application:
    name: repository
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    #user:
    url: jdbc:mysql://localhost:3306/yugh?useUnicode=true&amp&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false&serverTimezone=GMT
    username: root
    password: mac12345
    driverClassName: com.mysql.cj.jdbc.Driver
    # goods:
    #  url: jdbc:mysql://localhost:3306/sys?useUnicode=true&amp&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false
    #  username: root
    #  password: mac12345
    #  driverClassName: com.mysql.jdbc.Driver

#log
logging:
  level:
    org.yugh.coral.repository: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: TRACE
    org.springframework.web.reactive: TRACE
    reactor.ipc.netty: TRACE


#reg
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/


#lb
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000


#feign
feign:
  hystrix:
    enabled: false

#hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000