spring:
  application:
    name: monitor
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config

#eureka-gateway-monitor-config 每个端口+1
server:
  port: 8703

#eureka注册配置
eureka:
  instance:
    #使用IP注册
    prefer-ip-address: true
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 30
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8700/eureka/

ribbon:
  #请求处理超时时间
  ReadTimeout: 2000
  ConnectTimeout: 2000

#要监听的微服务列表
turbine:
  app-config: product
  cluster-name-expression: "'default'"
