spring:
  application:
    name: zuul

server:
  port: 8702

#eureka注册配置
eureka:
  instance:
    #使用IP注册
    prefer-ip-address: true
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 30
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 90
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/

# route connection
zuul:
  host:
    #单个服务最大请求
    max-per-route-connections: 20
    #网关最大连接数
    max-total-connections: 200
    #routes to serviceId
    routes:
      api-product.path: /api/product/**
      api-product.serviceId: product
      api-customer.path: /api/customer/**
      api-customer.serviceId: customer



#移除url同时移除服务
auth-props:
  #accessIp: 127.0.0.1
  #accessToken: admin
  #authLevel: dev
  #服务
  api-urlMap: {
    product: 1&2,
    customer: 1&1
  }
  #移除url同时移除服务
  exclude-urls:
    - /pro
    - /cust


#断路时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000

#ribbon
ribbon:
  ReadTimeout: 15000
  ConnectTimeout: 15000
  SocketTimeout: 15000
  eager-load:
    enabled: true
    clients: product, customer

