server:
  port: 9413
spring:
  application:
    name: zipkin-response
  #rabbit
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


  #zipkin
  zipkin:
    base-url: http://localhost:9411/
    #sender:
      #rabbit
      #type: rabbit
  #sleuth
  sleuth:
    sampler:
      #1.0表示以 100% 的概率将链路的数据上传给 Zipkin Server
      probability: 1.0
  #overriding
  main:
    allow-bean-definition-overriding: true


#eureka注册配置
eureka:
  instance:
    #使用IP注册
    prefer-ip-address: true
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 30
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: http://localhost:8700/eureka/

#log
logging:
  level:
    #这个是设置feign的一个日志级别,key-val的形式设置
    org.springframework.cloud.openfeign: DEBUG

#health
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS