# server
server:
  port: 7071
  #
  jetty:
    max-threads: 1000
    min-threads: 20

# application
spring:
  application:
    name: plugin-client
  # profiles
#  profiles:
#    active: server
  # overriding
  main:
    allow-bean-definition-overriding: true
  # As Spring Cloud Ribbon is in maintenance mode
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false

## disable
#plugin:
#  # Jetty default Max/Min/IdleTimeout Con Thread 200/8/60000ms
#  jetty:
#    config:
#      enabled: true
#    initial-value:
#      max-thread: 500
#      min-thread: 20


  # caffeine
  cache:
    type: CAFFEINE
    caffeine:
      spec: initialCapacity=100,maximumSize=1000,expireAfterWrite=30s
  # redis
  redis:
    port: 6379
    host: localhost
    lettuce:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
    cache-plugin:
      key-prefix: plugin:client
      expire: 30
      enabled: true


# management
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always

# hystrix

# ribbon


# eureka
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: localhost:8761/eureka/
#    enabled: false
