server:
  port: 8081

spring:
  # profiles
  profiles:
    active: local
  # overriding
  main:
    allow-bean-definition-overriding: true
    # Spring Boot’s lazy initialization feature is switched on
    # lazy-initialization: true
  # caffeine
  cache:
    type: CAFFEINE
    caffeine:
      spec: initialCapacity=100,maximumSize=1000,expireAfterWrite=30s
  # redis
  redis:
    port: 6379
    host: localhost
    lettuce:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 10
        min-idle: 5
    cache-plugin:
      key-prefix: plugin:client
      expire: 30
      enabled: true
#  rsocket:
#    server:
#      mapping-path: /
#      port: 8082
