#port
server:
  port: 8707
#setting
spring:
  application:
    name: repository

#log
logging:
  level:
    org.yugh.gatewaynew: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: TRACE
    org.springframework.web.reactive: TRACE
    reactor.ipc.netty: TRACE


#reg
eureka:
    instance:
      prefer-ip-address: true
    client:
        serviceUrl:
          defaultZone: http://localhost:8700/eureka/


#lb
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000


#feign
feign:
  hystrix:
    enabled: false

#hystrix
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000