server:
  port: 8706
#setting
spring:
  application:
    name: gateway-new
  #redis
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 5000
  #遇到相同名字，允许覆盖
  main:
    allow-bean-definition-overriding: true
  #gateway
  cloud:
    gateway:
      #注册中心服务发现
      discovery:
        locator:
          #开启通过服务中心的自动根据 serviceId 创建路由的功能
          enabled: true
      routes:
        #自测服务1
        - id: CompositeDiscoveryClient_CUSTOMER
          uri: lb://CUSTOMER
          order: 1
          predicates:
            # 跳过自定义是直接带实例名 必须是大写 同样限流拦截失效
            - Path= /api/customer/**
          filters:
            - StripPrefix=2
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@remoteAddrKeyResolver}"
                #限额配置
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        #用户微服务
        - id: CompositeDiscoveryClient_DATAWORKS-USERCENTER-WEB
          uri: lb://DATAWORKS-USERCENTER-WEB
          order: 0
          predicates:
            - Path= /api/user/**
          filters:
            - StripPrefix=1
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@remoteAddrKeyResolver}"
                #限额配置
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
          #请求路径选择自定义会进入限流器
          default-filters:
            - AddResponseHeader=X-Response-Default-Foo, Default-Bar
            - name: remoteAddrKeyResolver
              args:
                key-resolver: "#{@remoteAddrKeyResolver}"
              #断路异常跳转
            - name: Hystrix
              args:
                #网关异常或超时跳转到处理类
                name: fallbackcmd
                fallbackUri: forward:/fallbackController

#自定义过滤链接
auth-skip:
  api-urls:
    - /task/sch/config
    - /health
    - /task/callback
    - /task/exec
    - /task/workspace
    - /user/group



#日志输出
logging:
  level:
    org.yugh.gatewaynew: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG


#注册中心
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/

#健康监控
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

#负载均衡
ribbon:
  ReadTimeout: 10000


#feign
feign:
  hystrix:
    enabled: true

#熔断超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000