server:
  port: 8081

# log
logging:
  level:
    reactor.ipc.netty.http: DEBUG
    reactor.ipc.netty.channel: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.http.server.reactive: DEBUG

spring:
  # datasource -local
  datasource:
    username: root
    password: mac12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_order?characterEncoding=utf-8&useSSL=false
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
